markdown: kramdown
url: ''
baseurl: null
title: Priyanshu Chandel
description: Hello, I'm Priyanshu Chandel
site-image: /WhatATheme/assets/images/meta.jpg
site-keywords: 'Priyanshu, chandel, Priyanshu chandel, Priyanshu Kumar, Priyanshu youtube, Priyanshu github'
favicon-url: null
heroimage: >-
  https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
email: chandelpriyanshu8@outlook.com
facebook_username: priyanshu.pr
twitter_username: PRIYANSHUCHAN
instagram_username: thedevslot
linkedin_username: prianshuchandel
github_username: PriyanshuChandel
youtube_channel_id: UCYNfy-K2fuNVW8ydTDmvqmA
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /
google-analytics: UA-163806439-1
disqus-shortname: thedevslot
author-name: Priyanshu Chandel
author-image: >-
  /assets/images/self.JPG
author-about: >-
  I am a young, enthusiastic coder with a passion for Python programming. I'm proficient in Python and learning HTML, CSS and JS. I started a YouTube channel where I'll post videos related to technology/computer/coding. For additional details, feel free to reach out to me through email or social media.
author-url: 'https://github.com/PriyanshuChandel'
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
permalink: 'blog/:title'
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
