markdown: kramdown
url: https://priyanshuchandel.github.io
baseurl: 
title: Priyanshu Chandel 
contact: +918285775109
description: Imaginative and curious about coading
site-image: >-
  /assets/images/site-logo.png
navbar-image: >-
  /assets/images/site-logo.png
showcase-image: >-
  /assets/images/logo.png   
site-keywords: 'Priyanshu, chandel, PriyanshuChandel, Priyanshu chandel, Priyanshu Kumar, Priyanshu youtube, priyanshuchandel github, Priyanshu github, Priyanshu'
favicon-url: null
heroimage: >-
  /assets/images/hero.gif
email: chandelpriyanshu8@outlook.com
facebook_username: priyanshu.pr
twitter_username: PRIYANSHUCHAN
instagram_username: /
linkedin_username: prianshuchandel
github_username: PriyanshuChandel
youtube_channel_id: UCYNfy-K2fuNVW8ydTDmvqmA
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: 313nzk5zhcqygple35neaaqqh3qe?si=13d008570b144b07
google-analytics: G-JX7T5Z8SZ9
chatbot-pageid: 111048631902429
disqus-shortname: /
author-name: Priyanshu Chandel
author-image: >-
  /assets/images/self.jpg
author-about: >-
  Hi there! My name is Priyanshu Chandel and I am a skilled individual with a strong foundation in Python programming. I am constantly seeking new opportunities to expand my knowledge and skills, which is why I have decided to dive into the world of web development by learning HTML, CSS, and JavaScript.

  With my intermediate level of Python knowledge, I am well equipped to tackle the challenges of web development. My goal is to combine my programming skills with my growing knowledge of HTML, CSS, and JavaScript to create stunning and functional websites.
  
  I am passionate about using technology to solve problems and make a difference in the world. This drive, combined with my strong work ethic, makes me a dedicated and reliable individual who is always striving to improve and achieve success. For additional details, feel free to reach out to me through email or social media.
author-url: 'https://github.com/PriyanshuChandel'
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
permalink: 'blog/:title'
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
