markdown: kramdown
url: ''
baseurl: null
title: Priyanshu Chandel
contact: +918285775109
description: Imaginative and curious about coading
site-image: >-
  /assets/images/site-logo.png
navbar-image: >-
  /assets/images/site-logo.png
showcase-image: >-
  /assets/images/logo.png   
site-keywords: 'Priyanshu, chandel, PriyanshuChandel, Priyanshu chandel, Priyanshu Kumar, Priyanshu youtube, Priyanshu github, Priyanshu'
favicon-url: null
heroimage: >-
  /assets/images/hero.jpg
email: chandelpriyanshu8@outlook.com
facebook_username: priyanshu.pr
twitter_username: PRIYANSHUCHAN
instagram_username: /
linkedin_username: prianshuchandel
github_username: PriyanshuChandel
youtube_channel_id: UCYNfy-K2fuNVW8ydTDmvqmA
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: 313nzk5zhcqygple35neaaqqh3qe?si=13d008570b144b07
google-analytics: UA-163806439-1
disqus-shortname: /
author-name: Priyanshu Chandel
author-image: >-
  /assets/images/self.jpg
author-about: >-
  I am a enthusiastic coder with a passion for Python programming. I'm proficient in Python and learning HTML, CSS and JS. I started a YouTube channel where I'll post videos related to technology/computer/coding. For additional details, feel free to reach out to me through email or social media.
author-url: 'https://github.com/PriyanshuChandel'
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
permalink: 'blog/:title'
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
